services:
  web:
    build:
      context: ./src
      dockerfile: dockerfile
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["uvicorn", "app:app", "--host=0.0.0.0", "--reload"]

  db:
    image: postgres:14.8-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5431:5432"